[package]
name = "disklist"
version = "0.0.0-dev"
edition = "2021"

[lib]
name = "disklist"
crate-type = ["cdylib"]

[dependencies]
flate2 = "1.1.5"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
