from typing import Any, Optional

class Presence:
    client_id: int
    rpc: Optional[Any]
    start_time: float
    auto_update: bool
    update_interval: int
    _thread: Optional[Any]
    _stop_event: Any
    _lock: Any
    _connected: bool

    def __init__(self, client_id: int, auto_update: bool = True, update_interval: int = 15) -> None: ...
    
    @property
    def connected(self) -> bool: ...
    
    @connected.setter
    def connected(self, value: bool) -> None: ...

    def connect(self) -> None: ...
    def _background_update(self) -> None: ...
    def update(self, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
    def reconnect(self) -> None: ...
    
    def __enter__(self) -> "Presence": ...
    def __exit__(self, exc_type: Optional[type], exc_val: Optional[BaseException], exc_tb: Optional[Any]) -> None: ...
    def __dealloc__(self) -> None: ...