name: Accuracy Report
about: Report an accuracy issue in PyNES
title: ''
labels: ''
assignees: ''
body:
  - type: textarea
    attributes:
      label: Describe the Accuracy Issue
      description: A clear and concise description of what the accuracy issue is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Load ROM '...'
        2. Go to '...'
        3. Observe incorrect behavior (e.g., graphical glitch, sound issue, game logic error)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen (e.g., how it behaves on real hardware or other emulators).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or video links to help explain your problem.
    validations:
      required: false
  - type: input
    attributes:
      label: ROM Name
      description: The name of the ROM file.
    validations:
      required: true
  - type: input
    attributes:
      label: ROM Hash (SHA1 or MD5)
      description: The hash of the ROM file to ensure exact reproduction.
    validations:
      required: false
  - type: input
    attributes:
      label: ROM Version
      description: The version of the ROM (e.g., USA, Europe, Japan).
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: PyNES Version
      description: The version of PyNES you are using (e.g., 0.1.0, or commit hash if building from source).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false