name: Feature Request
about: Suggest an idea for improving PyNES
title: 'Feature Request'
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: What feature would you like to see added?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: If applicable, describe any alternative solutions or features you have considered.
    validations:
      required: false