name: Feature Request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''
body:
  - type: textarea
    attributes:
      label: What feature would you like to see added?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: If applicable, describe any alternative solutions or features you have considered.
    validations:
      required: false